[build]
functions = "./netlify/functions"
  command = "npm run build"
  publish = "dist"

  [functions]
  external_node_modules = ["express","serverless-http"]
  node_bundler = "esbuild"

  [[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true